version: "3.9"
services:
  twenty-dev:
    build: 
      context: ../..
      dockerfile: ./infra/dev/twenty-dev/Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
      - "6006:6006"
    volumes:
      - ../..:/app
      - twenty_node_modules_front:/app/front/node_modules
      - twenty_node_modules_server:/app/server/node_modules
    depends_on:
      - postgres
  twenty-docs:
    build:
      context: ../..
      dockerfile: ./infra/dev/twenty-docs/Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ../../docs:/app/docs
      - twenty_node_modules_docs:/app/docs/node_modules
  postgres:
    build: ./postgres
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: twenty
    ports:
      - "5432:5432"
  rest:
    container_name: pg_postgrest
    image: postgrest/postgrest:v10.0.0
    restart: unless-stopped
    ports:
      - 7001:3000
    environment:
      PGRST_DB_URI: postgres://postgres:twenty@postgres:5432/default
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: anon
    depends_on:
      - postgres
  graphiql:
    container_name: pg_graphiql
    image: nginx
    volumes:
      - ./dockerfiles/graphiql:/usr/share/nginx/html
    ports:
      - 4000:80
    depends_on:
      - rest
volumes:
  db_data:
  twenty_node_modules_front:
  twenty_node_modules_server:
  twenty_node_modules_docs: